### ISSUE TITLE
Implement onModuleDestroy

### ISSUE THREAD

**Issue by marktran** [xp-fly/nestjs-redis#1]
Just tried out this package and noticed that it keeps the connection to redis open and prevents `jest` from cleanly finishing. Should this implement `onModuleDestroy` similar to `@nestjs/typeorm`?

https://github.com/nestjs/typeorm/blob/master/lib/typeorm-core.module.ts#L101

**Comment by xp-fly** [comment]
@marktran the onModuleDestroy event called when app.close(), it means app is closed and can`t services for any request. i think it is necessary to implement. i have no idea why @nestjs/typeorm implement it. =. =

**Comment by marktran** [comment]
I think this package should actually implement this. You need it to properly clean up open connections when the module is destroyed. Frameworks like `jest` will display a warning if it can't cleanly finish.
